src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/GroupsRule.java
=> fix: empty user list should not disable groups rule entirely

README.md, src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/ExternalAuthenticationAsyncRule.java, src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/GroupsProviderAuthorizationAsyncRule.java, src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/LdapAuthenticationAsyncRule.java, src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/LdapAuthorizationAsyncRule.java, src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/ProxyAuthSyncRule.java, src/main/java/org/elasticsearch/plugin/readonlyrest/utils/ConfigReaderHelper.java, src/test/java/org/elasticsearch/plugin/readonlyrest/rules/GroupsProviderAuthorizationAsyncRuleTests.java, src/test/java/org/elasticsearch/plugin/readonlyrest/rules/LdapAuthAsyncRuleTests.java, src/test/java/org/elasticsearch/plugin/readonlyrest/rules/LdapAuthenticationAsyncRuleTests.java, src/test/java/org/elasticsearch/plugin/readonlyrest/rules/LdapAuthorizationAsyncRuleTests.java, src/test/java/org/elasticsearch/plugin/readonlyrest/rules/ProxyAuthRuleTests.java, src/test/java/org/elasticsearch/plugin/readonlyrest/utils/containers/ESWithReadonlyRestContainer.java, src/test/java/org/elasticsearch/plugin/readonlyrest/utils/containers/LdapContainer.java, src/test/java/org/elasticsearch/plugin/readonlyrest/utils/containers/WaitWithRetriesStrategy.java, src/test/java/org/elasticsearch/plugin/readonlyrest/utils/containers/WireMockContainer.java, src/test/resources/external_authentication_test_elasticsearch.yml, src/test/resources/groups_provider_authorization_test_elasticsearch.yml, src/test/resources/ldap_first_option_test_elasticsearch.yml, src/test/resources/ldap_second_option_test_elasticsearch.yml
I've just realised that configuration created in my previous PR could be better (it worked, but could cause error). This is fix for my bad configuration design.
=> Configuration fixes

src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/LdapAuthorizationAsyncRule.java, src/test/java/org/elasticsearch/plugin/readonlyrest/rules/LdapAuthorizationAsyncRuleTests.java
when LDAP returned no group, user was authorized
=> fixed: ldap group authorization bug

core/src/main/java/org/elasticsearch/plugin/readonlyrest/utils/BasicAuthUtils.java, core/src/test/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/AuthKeyRuleTests.java, core/src/test/java/org/elasticsearch/plugin/readonlyrest/utils/BasicAuthUtilsTests.java
When user has a password ending with ":" authentication fails.When user has a password ending with ":" authentication fails.
=> Password ending in ':' fails

core/build.gradle, core/src/test/java/tech/beshu/ror/acl/definitions/ldaps/UnboundidAuthenticationLdapClientTests.java, core/src/test/resources/test_example.ldif, integration-tests/src/test/eshome/config/log4j2.properties, integration-tests/src/test/java/tech/beshu/ror/integration/LdapAutenticationLocalAuthorizationTests.java, integration-tests/src/test/resources/ldap_authc_local_authz/elasticsearch.yml, integration-tests/src/test/resources/ldap_separate_authc_authz_mixed_local/ldap.ldif, tests-utils/src/main/java/tech/beshu/ror/utils/httpclient/RestClient.java
seems that unicodes are handed properly by ROR (ldap case)
=> added: more ldap tests to prove that unicode characters works

core/src/main/java/tech/beshu/ror/acl/blocks/rules/impl/KibanaAccessSyncRule.java
Allow for POST to PTH:/.kibana/doc/url.*/_create?refresh=wait_for
fixes #384
=> enable kibana_access:ro to create short urls in es6.3+

es53x/src/main/java/tech/beshu/ror/es/IndexLevelActionFilter.java, es55x/src/main/java/tech/beshu/ror/es/IndexLevelActionFilter.java, es60x/src/main/java/tech/beshu/ror/es/IndexLevelActionFilter.java, es61x/src/main/java/tech/beshu/ror/es/IndexLevelActionFilter.java, es63x/src/main/java/tech/beshu/ror/es/IndexLevelActionFilter.java, es66x/src/main/java/tech/beshu/ror/es/IndexLevelActionFilter.java, es70x/src/main/java/tech/beshu/ror/es/IndexLevelActionFilter.java
fix: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/464
=> removed: es.set.netty.runtime.available.processors setting

integration-tests-scala/src/test/resources/actions/readonlyrest.yml, integration-tests-scala/src/test/scala/tech/beshu/ror/integration/ActionsTests.scala, tests-utils/src/main/java/tech/beshu/ror/utils/elasticsearch/ActionManager.java
according to: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/451
=> added: delete action integration tests

core/src/main/scala/tech/beshu/ror/acl/factory/RawRorConfigBasedCoreFactory.scala, core/src/main/scala/tech/beshu/ror/adminapi/AdminRestApi.scala, core/src/main/scala/tech/beshu/ror/boot/ReadonlyRest.scala, core/src/main/scala/tech/beshu/ror/configuration/FileConfigLoader.scala, core/src/main/scala/tech/beshu/ror/configuration/RawRorConfig.scala, core/src/test/resources/boot_tests/bad_index_config/elasticsearch.yml, core/src/test/resources/boot_tests/bad_index_config/readonlyrest_index.yml, core/src/test/resources/boot_tests/forced_file_loading_bad_config/elasticsearch.yml, core/src/test/resources/boot_tests/forced_file_loading_bad_config/readonlyrest.yml, core/src/test/resources/boot_tests/forced_file_loading_malformed_config/elasticsearch.yml, core/src/test/resources/boot_tests/forced_file_loading_malformed_config/readonlyrest.yml, core/src/test/resources/boot_tests/index_config_not_exists_bad_file_config/elasticsearch.yml, core/src/test/resources/boot_tests/index_config_not_exists_bad_file_config/readonlyrest.yml, core/src/test/resources/boot_tests/index_config_not_exists_malformed_file_config/elasticsearch.yml, core/src/test/resources/boot_tests/index_config_not_exists_malformed_file_config/readonlyrest.yml, core/src/test/resources/boot_tests/malformed_index_config/elasticsearch.yml, core/src/test/resources/boot_tests/malformed_index_config/readonlyrest_index.yml, core/src/test/scala/tech/beshu/ror/unit/boot/ReadonlyRestStartingTests.scala, tests-utils/src/main/java/tech/beshu/ror/utils/containers/ESWithReadonlyRestContainer.java
=> changed: ROR starting algorithm improvement

core/src/main/scala/tech/beshu/ror/accesscontrol/factory/JsonConfigStaticVariableResolver.scala, core/src/test/scala/tech/beshu/ror/integration/VariableResolvingYamlLoadedAccessControlTests.scala
Fix (ES) wrong non-string ENV variables resolving
=> fixed: non-string ENV variables proper resolving

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/RuleOrdering.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/ProxyAuthRuleDecoder.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/ProxyAuthRuleSettingsTests.scala, gradle.properties
Fix (ES) issue with backward compatibility of proxy_auth settings
=> fixed: issue with backward compatibility of proxy_auth settings

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/JwtAuthRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/RorKbnAuthRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/utils/ClaimsOps.scala, core/src/main/scala/tech/beshu/ror/utils/uniquelist/UniqueList.scala, es55x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es60x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es61x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es62x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es63x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es66x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es70x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es73x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es74x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, gradle.properties, integration-tests-scala/src/test/scala/tech/beshu/ror/integration/MustacheLangTests.scala, integration-tests/src/test/eshome/config/readonlyrest.yml, tests-utils/src/main/scala/tech.beshu.ror.utils/elasticsearch/SearchManager.scala
Fix (ES) /_render/template request NPE
Enhancement (ES) less verbose logs in JWT rules
=> fixed: _render/template bug

core/src/main/scala/tech/beshu/ror/utils/yaml/parser.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/AuditingSettingsTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/CoreFactoryTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/YamlParserTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/BaseRuleSettingsDecoderTest.scala, core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala, gradle.properties
**Enhancement**  Better config validation - prevent duplicated keys in readonlyrest.yml
=> [Rordev-19] Prevent duplicated keys in readonlyrest.yml config

core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala
**Fix** Don't log 'RESOLVED' in 'HIS' if it's going to be empty
=> [Rordev-178] Don't log 'RESOLVED' when empty

audit/src/main/scala/tech/beshu/ror/audit/AuditRequestContext.scala, audit/src/main/scala/tech/beshu/ror/audit/instances/DefaultAuditLogSerializer.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/logging/AuditingTool.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/request/RequestContext.scala, integration-tests/src/test/java/tech/beshu/ror/integration/EnabledAuditingToolsTests.java, integration-tests/src/test/resources/enabled_auditing_tools/elasticsearch.yml
**Enhancement** Enrich logs and audit with attempted username
=> [Rordev-181] Add attempted user to default audit log serializer

core/src/test/scala/tech/beshu/ror/unit/boot/BuildInfoReaderTest.scala, es51x/build.gradle, es52x/build.gradle, es53x/build.gradle, es55x/build.gradle, es60x/build.gradle, es61x/build.gradle, es62x/build.gradle, es63x/build.gradle, es66x/build.gradle, es70x/build.gradle, es72x/build.gradle, es73x/build.gradle, es74x/build.gradle, gradle.properties
... to be able to build ROR without .git
=> removed: problematic plugin

bin/build.sh, es74x-cloud/gradle.properties, es74x-cloud/src/main/scala/tech/beshu/ror/proxy/es/CreateEsHttpRequest.scala, es74x-cloud/src/main/scala/tech/beshu/ror/proxy/es/EsRestServiceSimulator.scala, es74x/build.gradle, es74x/gradle.properties
🧐Enhancement (ES) ES 7.6.0 support
=> es 7.6.0 support

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/variables/runtime/RuntimeResolvableVariable.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/variables/runtime/RuntimeResolvableVariableCreator.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/variables/runtime/VariableContext.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/variables/RuntimeResolvableVariablesTests.scala
#565 
🧐Enhancement (ES) new acl:available_groups variable
=> Add available groups as dynamic variable

core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/logging/AccessControlLoggingDecorator.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/request/EsRequestContext.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/request/RequestInfoShim.scala, core/src/main/scala/tech/beshu/ror/utils/ScalaOps.scala, core/src/test/scala/tech/beshu/ror/integration/LdapConnectivityCheckYamlLoadedAccessControlTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/request/EsRequestContextTests.scala, es51x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es52x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es53x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es55x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es60x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es61x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es62x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es63x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es66x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es70x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es72x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es73x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, es74x/src/main/scala/tech/beshu/ror/es/request/RequestInfo.scala, integration-tests/src/test/java/tech/beshu/ror/integration/LdapIntegrationGroupsTests.java
🐞Fix (ES) support for multiple header values
🧐Enhancement (ES/KBN) handling of encoded ROR headers in Authorization header values
=> [RORDEV-227] multiple values for authorization header

core/src/main/java/tech/beshu/ror/ZeroKnowledgeIndexFilter.java, gradle.properties
🐞Fix (ES) Remote indices searching fix
=> [RORDEV-243] remote indices searching fix

core/src/main/java/tech/beshu/ror/ZeroKnowledgeIndexFilter.java, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/IndicesRuleTests.scala
🐞Fix (ES) Remote indices searching fix
=> [RORDEV-243] remote indices searching fix 

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/metadata/MetadataValue.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/KibanaAccessRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/KibanaAccessRuleTests.scala
Enhancement: kibana_access can be explicity set to unrestricted
=> RORDEV-251 Adding unrestricted kibana access

core/build.gradle, core/src/main/scala/tech/beshu/ror/utils/yaml/parser.scala, ror-shadowed-libs/build.gradle
Fix (ES) fixed: potential memory leak for ES 7.7.x and above
=> [RORDEV-307] snakeyaml memory leak

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/IndicesRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala, es79x/src/main/scala/tech/beshu/ror/es/dlsfls/DocumentFieldReader.scala, gradle.properties, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/CrossClusterCallsSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/SearchManager.scala
🐞Fix (ES) cross cluster search issue fix for X-Pack _async_search action
=> [RORDEV-320] fixed: cross cluster search with _async_search

bin/build.sh, es55x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es60x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es61x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es62x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es63x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es66x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es70x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es72x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es73x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es74x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es77x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es78x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, es79x/src/main/scala/tech/beshu/ror/es/request/context/BaseEsRequestContext.scala, gradle.properties
🐞Fix (ES) remote address extracting issue
=> [RORDEV-326] remote address extracting fix

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/BaseHeaderRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/HeadersAndRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/HeadersOrRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/utils/SimpleMatcher.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/HeadersRulesDecoders.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/HeaderOrRuleTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/HeadersAndRuleTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/HeadersAndRuleSettingsTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/HeadersOrRuleSettingsTests.scala, core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala, gradle.properties
🧐Enhancement (ES) negation support in headers rules
=> [RORDEV-331] support of header requirement negation in all header rules

bin/build.sh, es79x/build.gradle, es79x/gradle.properties
=> ES 7.9.1 support

bin/build.sh, es79x/gradle.properties, eshome/config/jvm.options, integration-tests/src/test/resources/jvm.options, tests-utils/build.gradle, tests-utils/src/main/scala/tech/beshu/ror/utils/containers/EsContainer.scala
=> added: support for ES 7.9.2

core/src/main/scala/tech/beshu/ror/utils/JavaConverters.scala, es55x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es55x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es60x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es60x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es61x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es61x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es62x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es62x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es63x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es63x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es66x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es66x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es70x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es70x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es72x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es72x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es73x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es73x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es74x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es74x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es77x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es77x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es78x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es78x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, es79x/src/main/scala/tech/beshu/ror/es/request/handler/regular/RegularRequestHandler.scala, es79x/src/main/scala/tech/beshu/ror/es/utils/ThreadContextOps.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/MiscSuite.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/base/BaseIndexApiSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/IndexManager.scala
🐞Fix (ES) don't remove response warning headers
=> RORDEV-245 [ES] Missing Warning response header

core/src/main/scala/tech/beshu/ror/Constants.java, core/src/main/scala/tech/beshu/ror/configuration/loader/LoadRawRorConfig.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/proxy/RorProxyInstance.scala
🐞Fix (ES) index resolve action should be treated as readonly action
=> [RORDEV-359] indices:admin/resolve/* action as RO actions

es55x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es60x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es61x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es62x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es63x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es66x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es70x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es72x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, es73x/src/main/scala/tech/beshu/ror/es/request/context/types/GetRepositoriesEsRequestContext.scala, gradle.properties, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/SnapshotAndRestoreApiSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/SnapshotManager.scala
🐞Fix (ES) /_snapshot and /_snapshot/_all should behave the same
=> [RORDEV-363] /_snapshot and /_snapshot/_all should behave the same

bin/build.sh, es79x/gradle.properties
=> [RORDEV-372] ES 7.9.3 support

bin/build.sh, es66x/gradle.properties
=> [RORDEV-373] ES 6.8.13 support 

.travis.yml, bin/build.sh, core/build.gradle, core/src/main/scala/tech/beshu/ror/utils/Hasher.scala, core/src/main/scala/tech/beshu/ror/utils/SuppressSha1Deprecation.java, core/src/main/scala/tech/beshu/ror/utils/yaml/parser.scala, ror-shadowed-libs/build.gradle, supressions_cve.xml
🧐Enhancement (ES)  CVE dependency scan
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/644
=> [RORDEV-349][ES] CVE vulnerabilities during scan of RoR plugin

bin/build.sh, core/build.gradle, core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala, es710x/gradle.properties, es710x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, gradle.properties, ror-shadowed-libs/build.gradle, supressions_cve.xml
🚀New (ES) 7.10.1 support
🚨Security Fix (ES) [CVE-2020-25649](https://nvd.nist.gov/vuln/detail/CVE-2020-25649)
details of CVE: https://github.com/FasterXML/jackson-databind/issues/2589
=> ES 7.10.1 support + CVE-2020-25649 patch

es63x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es63x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es66x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es66x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es70x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es70x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es710x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es710x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es72x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es72x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es73x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es73x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es74x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es74x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es77x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es77x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es78x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es78x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, es79x/src/main/scala/tech/beshu/ror/es/request/context/types/SqlIndicesEsRequestContext.scala, es79x/src/main/scala/tech/beshu/ror/es/utils/SqlRequestHelper.scala, eshome/config/jvm.options, eshome/modules/transport-netty4/plugin-descriptor.properties, eshome/plugins/readonlyrest/plugin-descriptor.properties, gradle.properties, integration-tests/src/test/resources/jvm.options, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/XpackApiSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/containers/EsImage.scala
🐞Fix (ES) SQL API - better handling of invalid query
=> [RORDEV-404] xpack _sql - better handling of invalid query

core/build.gradle, core/src/main/scala/tech/beshu/ror/configuration/loader/ConfigLoadingInterpreter.scala
🐞Fix (ES) CVE-2021-21290 vulnerability in netty
=> [RORDEV-435] Updated netty because of CVE-2021-21290 vulnerability

azure-pipelines.yml, bin/build.sh, es66x/src/main/scala/tech/beshu/ror/es/request/context/types/GetTemplatesEsRequestContext.scala, es711x/gradle.properties, gradle.properties, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/ImpersonationSuite.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/ReindexSuite.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/utils/IndexConfigInitializer.scala
…ways built, but uploaded only on master or develop
=> [RORDEV-332]fixed: building ROR for es66x

bin/build.sh, es711x/gradle.properties
=> [RODEV-459] ES 7.12.0 support

core/build.gradle, gradle.properties, integration-tests/src/test/scala/tech/beshu/ror/integration/proxy/XpackApiProxyTests.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/XpackApiSuite.scala, proxy/src/main/scala/tech/beshu/ror/proxy/es/EsActionRequestHandler.scala, proxy/src/main/scala/tech/beshu/ror/proxy/es/EsRestServiceSimulator.scala, proxy/src/main/scala/tech/beshu/ror/proxy/es/clients/RestHighLevelClientAdapter.scala, proxy/src/main/scala/tech/beshu/ror/proxy/es/exceptions.scala, proxy/src/main/scala/tech/beshu/ror/proxy/es/proxyaction/GenericPathIndicesRequest.scala, proxy/src/main/scala/tech/beshu/ror/proxy/es/proxyaction/GenericRequest.scala
and ...
🚨Security Fix (ES) [CVE-2021-21295](https://nvd.nist.gov/vuln/detail/CVE-2021-21295)
=> [RORDEV-460] ROR proxy _async_search support

core/build.gradle, ror-shadowed-libs/build.gradle, tests-utils/build.gradle
🐞Fix (ES) Fixed CVE-2021-27568
=> [RORDEV-475] Updated json-smart because of CVE-2021-27568

bin/build.sh, es711x/gradle.properties, es711x/src/main/scala/tech/beshu/ror/es/request/context/types/DeleteComponentTemplateEsRequestContext.scala, es711x/src/main/scala/tech/beshu/ror/es/request/context/types/DeleteComposableIndexTemplateEsRequestContext.scala
=> [RORDEV-492] ES 7.13.0 adaptations

core/build.gradle, gradle.properties, tests-utils/build.gradle
🚨Security Fix (ES) [Apache Commons Codec vulnerability](https://forum.readonlyrest.com/t/security-vulnerability-for-common-codec-1-10/1906)
=> [RORDEV-510] upgrade: apache commons common-codec

bin/build.sh, es66x/gradle.properties, es711x/gradle.properties
🚀New (ES) 7.13.2, 7.13.3, 6.8.17 support
=> ES 7.13.2 7.13.3 and 6.8.17

bin/build.sh, es714x/gradle.properties
🚀New (ES) Support for ES 7.14.1
=> ES 7.14.1 support

bin/build.sh, es714x/gradle.properties, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/IndexLifecycleManagementApiSuite.scala
🚀New (ES) Support for ES 7.15.0
=> [RORDEV-553] ES 7.15.0 support

bin/build.sh, es714x/gradle.properties
🚀New (ES) New Support for 7.15.2
=> ES 7.15.2 support

bin/build.sh, core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala, core/src/test/scala/tech/beshu/ror/unit/acl/domain/TemplateNamePatternTests.scala, es714x/gradle.properties, gradle.properties
🐞Fix (ES) [Adding policy to index template bug](https://forum.readonlyrest.com/t/forbidden-by-readonlyrest-es-plugin-with-add-policy-to-index-template-action-in-kibana/1969)
=> [RORDEV-545] finding the most generic template name pattern 

es55x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es60x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es61x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es62x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es63x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es65x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es66x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es67x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es70x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es710x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es711x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es714x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es72x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es73x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es74x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es77x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es78x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, es79x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/SnapshotsStatusEsRequestContext.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/SnapshotAndRestoreApiSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/httpclient/RestClient.java
🐞Fix (ES) [/_snapshot/_status should return only running snapshots](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/756)
=> [RORDEV-566] fixed: get all snapshots in-progress case

bin/build.sh, es716x/gradle.properties
🚀New (ES) New Support for 7.16.2, 6.8.22
=> ES 7.16.2 and 6.8.22 support

bin/build.sh, es716x/gradle.properties
🚀New (ES) New Support for 7.16.3, 6.8.23
=> [RORDEV-599] ES 7.16.3 & 6.8.23 support

es60x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es61x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es62x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es63x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es65x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es66x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es67x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es70x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es710x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es711x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es714x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es716x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es72x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es73x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es74x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es77x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es78x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, es79x/src/main/scala/tech/beshu/ror/es/services/HighLevelClientAuditSinkService.scala, gradle.properties, proxy/src/main/scala/tech/beshu/ror/proxy/RorProxy.scala, proxy/src/main/scala/tech/beshu/ror/proxy/es/services/ProxyAuditSinkService.scala
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/765
=> [RORDEV-600] ROR does not longer support TSLv1.0

bin/build.sh, es710x/src/main/scala/tech/beshu/ror/es/services/EsServerBasedRorClusterService.scala, es711x/src/main/scala/tech/beshu/ror/es/services/EsServerBasedRorClusterService.scala, es714x/src/main/scala/tech/beshu/ror/es/services/EsServerBasedRorClusterService.scala, es716x/gradle.properties, es716x/src/main/scala/tech/beshu/ror/es/services/EsServerBasedRorClusterService.scala, es77x/src/main/scala/tech/beshu/ror/es/services/EsServerBasedRorClusterService.scala, es78x/src/main/scala/tech/beshu/ror/es/services/EsServerBasedRorClusterService.scala, es79x/src/main/scala/tech/beshu/ror/es/services/EsServerBasedRorClusterService.scala, gradle.properties
... only for es714x and es716x (no tests yet)
=> [RORDEV-611] datastream aliases and `indices` rule fix

bin/build.sh, es716x/gradle.properties
🚀New (ES) New Support for 7.17.1
=> ES 7.17.1 support

azure-pipelines.yml, ci/ci-lib.sh, ci/s3-uploader.sh, ci/upload-file-to-s3.sh, ror-tools/build.gradle
🚀New (ES) New Support for 8.0.0
=> [RORDEV-619] ES 8.0.0 support

core/build.gradle, core/src/main/scala/tech/beshu/ror/accesscontrol/logging/DeprecatedAuditLoggingDecorator.scala, core/src/main/scala/tech/beshu/ror/utils/AccessControllerHelper.scala, es81x/src/main/scala/tech/beshu/ror/es/ResponseFieldsFiltering.scala, gradle.properties
🚨Security Fix (ES) [CVE-2022-21653](https://nvd.nist.gov/vuln/detail/CVE-2022-21653)
=> [RORDEV-601] CVE-2022-21653

gradle.properties, ror-shadowed-libs/build.gradle
🚨Security Fix (ES) [CVE-2020-36518](https://nvd.nist.gov/vuln/detail/CVE-2020-36518)
=> [RORDEV-645] CVE-2020-36518

core/src/main/scala/tech/beshu/ror/accesscontrol/factory/JsonConfigStaticVariableResolver.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/IndicesRuleSettingsTests.scala
=> RORDEV-650 (WIP) Numeric string(s) array as indices rules argument won't pass decoder validation

bin/build.sh, bin/upload_es_artifacts.sh, es716x/gradle.properties, es81x/gradle.properties
🚀New (ES) New Support for 8.1.3 & 7.17.3
=> [RORDEV-659] ES 8.1.3 support

audit/build.gradle, core/build.gradle, es60x/build.gradle, es61x/build.gradle, es62x/build.gradle, es63x/build.gradle, es65x/build.gradle, es66x/build.gradle, es67x/build.gradle, es70x/build.gradle, es710x/build.gradle, es711x/build.gradle, es714x/build.gradle, es716x/build.gradle, es72x/build.gradle, es73x/build.gradle, es74x/build.gradle, es77x/build.gradle, es78x/build.gradle, es79x/build.gradle, es80x/build.gradle, es81x/build.gradle, gradle.properties, ror-shadowed-libs/build.gradle, ror-tools/build.gradle, supressions_cve.xml
🚨Security Fix (ES) [CVE-2020-13956](https://nvd.nist.gov/vuln/detail/CVE-2020-13956) & [CVE-2020-36518](https://nvd.nist.gov/vuln/detail/CVE-2020-36518)
=> [RORDEV-652][RORDEV-647] CVE-2022-23708 & CVE-2020-13956

core/build.gradle, es82x/build.gradle, tests-utils/build.gradle
🚨Security Fix (ES) [CVE-2022-25647](https://nvd.nist.gov/vuln/detail/CVE-2022-25647) & [CVE-2022-24823](https://nvd.nist.gov/vuln/detail/CVE-2022-24823)
=> [RORDEV-675] CVE-2022-25647, CVE-2022-24823

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/JwtAuthRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/LdapAuthorizationRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/RorKbnAuthRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/JwtAuthRuleDecoder.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/RorKbnAuthRuleDecoder.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/utils/CirceOps.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/JwtAuthRuleTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/RorKbnAuthRuleTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/JwtAuthRuleSettingsTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/RorKbnAuthRuleSettingsTests.scala, gradle.properties, tests-utils/src/main/scala/tech/beshu/ror/utils/httpclient/RestClient.scala
🚀New (ES) Added `groups_and` sub-rule for `ror_kbn_auth`, and `jwt_auth`
=> [RORDEV-655] Ror kibana rule and JWT auth rule with "groups_and" support

bin/build.sh, bin/upload_es_artifacts.sh, es82x/gradle.properties
🚀New (ES) New Support for 8.2.3
=> [RORDEV-691] ES 8.2.3 support

bin/build.sh, bin/upload_es_artifacts.sh, es83x/gradle.properties
=> [ES] 8.3.3 support

ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/EsPatchLoggingDecorator.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/utils/EsDirectory.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/utils/ModuleOpener.scala, ror-tools/src/main/scala/tech/beshu/ror/tools/RorToolsApp.scala
🐞Fix (ES) ROR tools fix for Windows OS
=> [RORDEV-719] Fix for ROR tools default ES path

bin/build.sh, bin/upload_es_artifacts.sh, es84x/gradle.properties
=> [RORDEV-727] ES 8.4.1 support

gradle.properties, ror-shadowed-libs/build.gradle
🚨Security Fix (ES) [CVE-2022-25857](https://nvd.nist.gov/vuln/detail/CVE-2022-25857)
=> [RORDEV-730] CVE-2022-25857

bin/build.sh, bin/upload_es_artifacts.sh, es84x/gradle.properties
=> [RORDEV-735] ES 8.4.2 support

ror-shadowed-libs/build.gradle, supressions_cve.xml
Fixes for:
CVE-2022-38752
CVE-2022-38751
CVE-2022-38750
CVE-2022-25857
CVE-2022-38749
=> [RORDEV-737] CVE fixes

bin/build.sh, bin/upload_es_artifacts.sh, es85x/gradle.properties
=> [RORDEV-779] ES 8.5.1 support

bin/build.sh, bin/upload_es_artifacts.sh, es85x/gradle.properties
=> [RORDEV-783] ES 8.5.2 support

audit/build.gradle, audit/src/main/scala/tech/beshu/ror/audit/adapters/DeprecatedAuditLogSerializerAdapter.scala, core/build.gradle, gradle.properties
🚨Security Fix (ES) [CVE-2022-36944](https://nvd.nist.gov/vuln/detail/CVE-2022-36944) in [audit scala 2.13 jar](https://mvnrepository.com/artifact/tech.beshu.ror/audit)
=> [RORDEV-789] CVE-2022-36944 in audit module

bin/build.sh, bin/upload_es_artifacts.sh, es716x/gradle.properties, es85x/gradle.properties
=> [RORDEV-790] ES 8.5.3 support

bin/build.sh, es716x/build.gradle, es716x/gradle.properties
=> [RORDEV-790] ES 7.17.8 support

core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala, es67x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es70x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es710x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es711x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es714x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es716x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es72x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es73x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es74x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es77x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es78x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es79x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es80x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es81x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es82x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es83x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es84x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, es85x/src/main/scala/tech/beshu/ror/es/RorTransportInterceptor.scala, gradle.properties
🐞Fix (ES) large report generation using data from a remote cluster with enabled x-pack security
=> [RORDEV-817] fix: large report generation + remote cluster

integration-tests/src/test/scala/tech/beshu/ror/integration/suites/CrossClusterCallsSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/SearchManager.scala
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/871
=> [RORDEV-817] integration tests

bin/build.sh, bin/upload_es_artifacts.sh, es85x/gradle.properties, es85x/src/main/scala/tech/beshu/ror/es/handler/response/FieldsFiltering.scala
=> [RORDEV-827] ES 8.6.0 support

es60x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es61x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es62x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es63x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es65x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es66x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es67x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es70x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es710x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es711x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es714x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es716x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es72x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es73x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es74x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es77x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es78x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es79x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es80x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es81x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es82x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es83x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es84x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, es85x/src/main/scala/tech/beshu/ror/es/handler/request/SearchRequestOps.scala, gradle.properties
🐞Fix (ES) NPE when `_search` with aggregations (script) and `fields` rule were used together
=> [RORDEV-826] _search with aggregations and `fields` rule cooperation

bin/build.sh, bin/upload_es_artifacts.sh, es85x/gradle.properties
=> [RODEV-840] ES 8.6.1 support

bin/build.sh, es716x/gradle.properties
=> [RORDEV-842] ES 7.17.9 support

bin/build.sh, bin/upload_es_artifacts.sh, es85x/gradle.properties
=> [RORDEV-852] ES 8.6.2 support

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/metadata/MetadataValue.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/metadata/UserMetadata.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/KibanaUserDataRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/common.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/kibana/KibanaUserDataRuleDecoder.scala, core/src/test/scala/tech/beshu/ror/integration/KibanaIndexAndAccessYamlLoadedAccessControlTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/kibana/KibanaUserDataRuleTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/kibana/KibanaUserDataRuleSettingsTests.scala, core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala, docs/api/ror-internal-api-swagger.yaml, gradle.properties, integration-tests/src/test/resources/current_user_metadata/readonlyrest.yml, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/CurrentUserMetadataSuite.scala
(no variables resolving support in the `metadata` filed yet)
=> [RORDEV-824] added: 'metadata' field in the 'kibana' rule

audit/build.gradle, audit/src/main/java/tech/beshu/ror/audit/adapters/JsonObjectJavaAdapter.java, audit/src/main/scala/tech/beshu/ror/audit/adapters/DeprecatedAuditLogSerializerAdapter.scala, core/build.gradle, core/src/main/scala/tech/beshu/ror/utils/yaml/parser.scala, gradle.properties, ror-shadowed-libs/build.gradle, supressions_cve.xml
🚨Security Fix (ES) CVE-2022-45688
=> [RORDEV-847] CVE fixes & dependencies upgrade

core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/kibana/KibanaUserDataRuleDecoder.scala, core/src/test/scala/tech/beshu/ror/integration/CurrentUserMetadataAccessControlTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/kibana/KibanaUserDataRuleSettingsTests.scala, integration-tests/src/test/resources/current_user_metadata/readonlyrest.yml
renamed `path` to `http_path` in `allowed_api_paths` extended format
=> [RORDEV-865] review improvements

bin/build.sh, bin/upload_es_artifacts.sh, es716x/gradle.properties, es87x/gradle.properties
🚀New (ES) 8.7.1, 7.17.10 support
=> [RORDEV-893][RORDEV-895] ES 8.7.1 & 7.17.10 support

bin/build.sh, bin/upload_es_artifacts.sh, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/definitions/UserDef.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/auth/BaseGroupsRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/common.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/definitions/UsersDefinitionsDecoder.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/auth/BaseGroupsRuleTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/GroupsRuleSettingsTests.scala, core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala, es716x/gradle.properties, es87x/gradle.properties, gradle.properties
🧐Enhancement (ES) external group name patterns support in the external to local groups mapping
=> [ROREV-899] wildcards support in external to local groups mapping

bin/build.sh, bin/upload_es_artifacts.sh, es88x/gradle.properties
=> [RORDEV-913] new ES 8.8.1 support

gradle.properties, supressions_cve.xml
Relates to: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/918
=> [RORDEV-916] Suppress CVE-2023-35116

bin/build.sh, bin/upload_es_artifacts.sh, es716x/gradle.properties, es88x/gradle.properties, gradle.properties, supressions_cve.xml
🚀New (Es) 8.8.2, 7.17.11 support
=> [RORDEV-927][RORDEV-928] ES 8.8.1, 7.17.11 support

es63x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es65x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es66x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es67x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es70x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es710x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es711x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es714x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es716x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es72x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es73x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es74x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es77x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es78x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es79x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es80x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es81x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es82x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es83x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es84x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es85x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es87x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es88x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, es89x/src/main/scala/tech/beshu/ror/es/utils/XPackSecurityAuthenticationHeader.scala, gradle.properties
🐞Fix (ES) stack-management screen fix in case of `xpack.security.enabled: true`
=> [RORDEV-937] stack-management screen fix in case of `xpack.security.enabled: true`

bin/build.sh, bin/upload_es_artifacts.sh, es89x/gradle.properties
=> [RORDEV-973] new ES 8.9.1 support

bin/build.sh, bin/upload_es_artifacts.sh, es810x/gradle.properties
=> [RORDEV-997] ES 8.10.1 support

bin/build.sh, es810x/gradle.properties
=> [RORDEV-999] ES 8.10.2 support

core/src/main/scala/tech/beshu/ror/Constants.java, gradle.properties
- Fix Logout-after-opening-Stack-management-Upgrading-asistant
=> RORDEV-1005 Logout-after-opening-Stack-management-Upgrading-asistant

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/ImpersonationWarning.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/RuleOrdering.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/auth/TokenAuthenticationRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/users/LocalUsersContext.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/variables/runtime/VariableContext.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/domain/security.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/ruleDecoders.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/auth/TokenAuthenticationRuleDecoder.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/auth/TokenAuthenticationRuleTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/TokenAuthenticationRuleSettingsTests.scala, core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala, gradle.properties
🚀New (ES) New token_authentication rule
=> [RORDEV-892] Token authentication rule

bin/build.sh, es717x/gradle.properties, es810x/gradle.properties
🚀New (ES) 8.10.3, 7.17.14 support
=> [RORDEV-1012][RORDEV-1014] new ES 8.10.3 & 7.17.14 support

bin/build.sh, es810x/gradle.properties
=> [RORDEV-1017] new ES 8.10.4 support

gradle.properties, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/utils/EsDirectory.scala
🐞Fix (ES) patching fix, when a non-default ES path is used (e.g. on K8s
=> [RORDEV-1031] problem with patcher when it's run with custom patch on k8s

audit/build.gradle, build-base/build.gradle, core/build.gradle, gradle.properties, supressions_cve.xml
🚨Security Fix (ES) CVE-2023-4586 CVE-2023-5072 CVE-2023-44487
=> [RORDEV-1036] CVE-2023-4586 CVE-2023-5072 CVE-2023-44487

bin/build.sh, es717x/gradle.properties
=> [RORDEV-1040] new ES 7.17.15 support

bin/run-pipeline.sh, es811x/gradle.properties
=> [RORDEV-1057] new ES 8.11.2 support

bin/run-pipeline.sh, es717x/gradle.properties, es811x/gradle.properties
🚀New (ES) 8.11.3, 7.17.16 support
=> [RORDEV-1060][RORDEV-1062] ES 8.11.3 & 7.17.16 support

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/BaseKibanaRule.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/KibanaActionMatchers.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/domain/indices.scala, docker-envs/base-ror-docker/run.sh, docker-envs/misc-clusters/simple-ror-cluster/ror/es/readonlyrest.yml, gradle.properties
🐞Fix (ES) Logout when a user with restricted `kibana.access` tried to see restore status of snapshots in Kibana
=> [RORDEV-1066] Problem with the restore status tab and `kibana.access` rule

core/build.gradle, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/definitions/ldap/implementations/UnboundidLdapAuthorizationService.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/definitions/ldap/implementations/UnboundidLdapNestedGroupsService.scala, core/src/test/resources/test_example.ldif, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/definitions/UnboundidLdapAuthorizationServiceInDefaultGroupSearchModeTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/definitions/UnboundidLdapAuthorizationServiceInGroupsFromUserAttributeModeTests.scala, gradle.properties, gradle/wrapper/gradle-wrapper.properties, ror-shadowed-libs/build.gradle, ror-tools-core/build.gradle, ror-tools/build.gradle, tests-utils/build.gradle
🐞Fix (ES) [LDAP nested groups names are properly escaped](https://forum.readonlyrest.com/t/support-kbn-ent-ldap-and-parentheses/2466)
=> [RORDEV-1070] fix: LDAP nested group names properly escaped

bin/run-pipeline.sh, es811x/gradle.properties
=> [RORDEV-1076] ES 8.11.4 support

bin/run-pipeline.sh, es717x/gradle.properties
=> [RORDEV-1086] ES 7.17.17 support

build-base/build.gradle, gradle.properties, ror-shadowed-libs/build.gradle, supressions_cve.xml, tests-utils/build.gradle
🚨Security Fix (ES) CVE-2023-51074
=> [RORDEV-1071] CVE-2023-51074

core/src/main/scala/tech/beshu/ror/accesscontrol/acl/AccessControlList.scala, core/src/test/scala/tech/beshu/ror/unit/acl/AccessControlListTests.scala, gradle.properties
=> [RORDEV-1109] fix: FORBID policy handling in case of ROR current user matadata request

integration-tests/src/test/scala/tech/beshu/ror/integration/suites/SnapshotAndRestoreApiSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/BaseManager.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/IndexManager.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/SnapshotManager.scala
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/986
=> [RORDEV-1084] fix: `es714` module tests

gradle.properties, integration-tests/src/test/resources/index_api/free_readonlyrest.yml, integration-tests/src/test/resources/index_api/nonfree_readonlyrest.yml, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/base/BaseIndexApiSuite.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es68xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es70xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es717xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es80xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es813xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es83xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es89xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/DummyAuthorizationInAuthorizationService.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/DummyAuthorizeInAuthorizationService.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/IndexManager.scala
🐞Fix (ES) proper `/_stats` handling when `xpack.security.enabled: true` is set
=> [ROEDEV-1166] fixed: Stats API when `xpack.security.enabled: true` is set

gradle.properties, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/base/EsPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/BytecodeJarModifier.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/AlwaysGrantApplicationPermission.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/DeactivateAuthenticationServiceInHttpTransport.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/DeactivateSecurityActionFilter.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/DeactivateSecurityServerTransportInterceptor.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/DummyAuthorizeInAuthorizationService.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/GetAuthenticationFromHeaderWhenMissingInTransient.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/MockAuthorizationInfoDuringRetrievingUserPrivilegesInAuthorizationService.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/MockAuthorizationInfoInAuthorizationService.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/MockAuthorizationInfoInSecurityContext.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/ModifyPolicyUtilClass.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/OpenModule.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/RepositoriesServiceAvailableForClusterServiceForAnyTypeOfNode.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/SnapshotsServiceAvailableForClusterServiceForAnyTypeOfNode.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/utils/RorToolsException.scala
🐞Fix (ES) patched files permission issue
=> [RORDEV-1174] fix: permissions for modified jar should be preserved

gradle.properties, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es68xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/Es711xPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/base/EsPatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/FilePatch.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/filePatchers/ElasticsearchJarPatchCreator.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/filePatchers/RorSecurityPolicyPatchCreator.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/filePatchers/XPackCoreJarPatchCreator.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/filePatchers/XPackIlmJarPatchCreator.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/filePatchers/XPackSecurityJarPatchCreator.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/FileModifier.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/utils/EsUtil.scala
🐞Fix (ES) Patching issue for Elasticsearch OSS versions
=> [RORDEV-1179] elasticsearch OSS images patching fix

core/build.gradle, gradle.properties
🚨Security Fix (ES) CVE-2024-34447
=> [RORDEV-1190] CVE-2024-34447

docker-image/ror-entrypoint-es6x.sh, docker-image/ror-entrypoint.sh, es67x/Dockerfile, es70x/Dockerfile, es710x/Dockerfile, es711x/Dockerfile, es714x/Dockerfile, es716x/Dockerfile, es717x/Dockerfile, es72x/Dockerfile, es73x/Dockerfile, es74x/Dockerfile, es77x/Dockerfile, es78x/Dockerfile, es79x/Dockerfile, es80x/Dockerfile, es810x/Dockerfile, es811x/Dockerfile, es812x/Dockerfile, es813x/Dockerfile, es814x/Dockerfile, es81x/Dockerfile, es82x/Dockerfile, es83x/Dockerfile, es84x/Dockerfile, es85x/Dockerfile, es87x/Dockerfile, es88x/Dockerfile, es89x/Dockerfile, gradle.properties
🐞Fix (ES) ECK-related: docker image user fix
=> [RORDEV-616] ECK-related docker images fix

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/elasticsearch/indices/clusterindices/AllClusterIndices.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/elasticsearch/indices/clusterindices/BaseIndicesProcessor.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/elasticsearch/indices/clusterindices/LocalIndicesManager.scala, core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/elasticsearch/indices/clusterindices/RemoteIndicesManager.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/indices/IndicesRuleDataStreamTests.scala, core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/indices/IndicesRuleLocalIndexTests.scala, core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala, gradle.properties, integration-tests/src/test/resources/cross_cluster_search/readonlyrest.yml, integration-tests/src/test/resources/search_api/readonlyrest.yml, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/CrossClusterCallsSuite.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/DataStreamApiSuite.scala, integration-tests/src/test/scala/tech/beshu/ror/integration/suites/SearchApiSuite.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/EnhancedDataStreamManager.scala, tests-utils/src/main/scala/tech/beshu/ror/utils/elasticsearch/IndexManager.scala
🐞Fix (ES) [data stream backing indices access issue with the indices rule](https://forum.readonlyrest.com/t/requested-index-doesnt-exist/2573)
=> [RORDEV-1223] Fix for datastream backing indices access in the indices rule

core/build.gradle, gradle.properties
🚨Security Fix (ES) [CVE-2024-47535](https://nvd.nist.gov/vuln/detail/CVE-2024-47535)
=> [RORDEV-1330] CVE-2024-47535

docker-image/ror-entrypoint-es6x.sh, docker-image/ror-entrypoint.sh, gradle.properties, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/base/EsPatchExecutor.scala, ror-tools/src/main/scala/tech/beshu/ror/tools/RorToolsApp.scala, ror-tools/src/test/scala/tech/beshu/ror/tools/RorToolsAppSuite.scala
🐞Fix (ES) Correct patching verification in ROR Docker image entrypoint
=> [RORDEV-1461] Docker image patching verification fix

gradle.properties, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/ModifyEntitlementRuntimePolicyParserClass.scala, ror-tools-core/src/main/scala/tech/beshu/ror/tools/core/patches/internal/modifiers/bytecodeJars/SecurityManagerShouldAllowReadingEsConfigFile.scala
🐞Fix (ES) [Patching issue in Elasticsearch 9.x, 8.19.x, and 8.18.x that caused startup failures on Java 17](https://forum.readonlyrest.com/t/ror-1-65-1-java-17/2841)
=> [RORDEV-1601] fixed: ROR patching issue for Elasticsearch 9.x & 8.19.x, 8.18.x on Java 17 
