sscarduzio/elasticsearch-readonlyrest-plugin

README.md
src/main/java/org/elasticsearch/rest/action/readonlyrest/ConfigurationHelper.java
src/main/java/org/elasticsearch/rest/action/readonlyrest/ReadonlyRestAction.java

This can come in handy when some parts of system needs to have full access to elastic search without exposing existance of some exceptions from RO rule.

Added basic authorization via HTTP Header to bypass all ACL checking.

---

README.md
src/main/java/org/elasticsearch/rest/action/readonlyrest/IPMask.java
src/main/java/org/elasticsearch/rest/action/readonlyrest/acl/ACL.java
src/main/java/org/elasticsearch/rest/action/readonlyrest/acl/ACLRequest.java
src/main/java/org/elasticsearch/rest/action/readonlyrest/acl/Rule.java
src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/ACLTest.java
src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/MarvelPassthroughACL.java

These changes were specifically made to allow AWS Lambda to be able to send requests to an ES cluster without having to open the entire cluster to the outside world.  
Currently, requests to an ES cluster (not an AWS managed ES cluster) from AWS Lambda may come from a large unknown pool of IP addresses.  By allowing access via an API Key that is made available to an AWS Lambda, you can allow access to just that Lambda.  Until AWS Lambdas can be run inside a VPC, this is a sufficient workaround.
Also, if your ES cluster is behind an AWS ELB, the addition of support for creating a rule using a subnet and retrieval of the remote address from the X-Forwarded-For header allows the host based rule parameter to still work since ELB attaches the X-Forwarded-For header to requests and also lives …

More ACL rules

---

README.md

Adjust on the 'uri_re' documentation, as the URI is the path after the 'HTTP Host', and not the full URL

Adjust on the 'uri_re' documentation

---

src/main/java/org/elasticsearch/plugin/readonlyrest/acl/ACL.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/Block.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/IPMask.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/AuthKeyRule.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S1213  The members of an interface declaration or class should appear in a pre-defined order
squid:UselessParenthesesCheck  Useless parentheses around expressions should be removed to prevent any misunderstanding
squid:S00122  Statements should be on separate lines
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1213
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck 
https://dev.eclipse.org/sonar/rules/show/squid:S00122 
Please let me know if you have any questions.
Zeeshan Asghar

General Code Improvement 1

---

src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/IndicesRule.java
src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/ACLTest.java

Hi Simone,
thank you for sharing the plugin! It is turning out to be useful for some of our projects. I just had a small issue when trying to restrict indexes access. I tested this only with Elasticsearch v.2.2.0 but I've looked over the older APIs and I would expect that to be ok for previous versions as well.
I am sharing back to seek for validation as well.
So this is what I have done:
Changed reflection call from Field 'indices' to method 'indices' as the method 'getDeclaredField' gets the fields, regardless of their accessibility but only for the current class, not any base classes that the current class might be inheriting from. And the field 'indices' is private and inherited. Changed it to access the public method instead. By doing that I can now use 'getMethod' and get to the …

Problem with Indices Rule

---

src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/ACLTest.java
src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/KibanaACLTest.java

The method `assertEquals` has the signature `void assertEquals(Object expected, Object actual)` and therefore the first argument should always be the one that is expected in order to avoid confusing messages such as this one: `expected:<actualValue> but was:<expectedValue>`

tests: swap arguments of assertEquals according to JUnit API

---

README.md
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/ACL.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/Block.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/User.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/UserNotConfiguredException.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/GroupsRule.java
src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/ACLTest.java
src/test/test_rules.yml

Hi Simone,
thank you for creating this plugin! :)
This change introduces a rule where one may specify user groups inside
access control blocks as well as define a dedicated list of users that are
members of these groups. A typical user entry consists of a username,
an auth key and a number of group memberships. A matching auth key in
combination with the correct group membership grants access under this rule.

feature: add group access rule and dedicated user list

---

build.sh
src/main/java/org/elasticsearch/plugin/readonlyrest/ConfigurationHelper.java
src/main/java/org/elasticsearch/plugin/readonlyrest/IndexLevelActionFilter.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/ACL.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/RequestContext.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/Block.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/MatcherWithWildcards.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/ActionsRule.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/IndicesRule.java
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/KibanaAccessRule.java
src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/ACLTest.java
src/test/java/org/elasticsearch/rest/action/readonlyrest/acl/test/KibanaACLTest.java
src/test/test_rules.yml

Fix for:
1. #111 Even if indices rule is set, _search?q=message:hellotest1 would return results from all indices.
2. #110 reverse indices wildcards + aliases support
3. Adding a few colored logs 
⚠️ This code is experimental, I tested it with success on the following multi-user Kibana + Logstash configuration:
```yml
readonlyrest:
enable: true
ssl:
enable: true
keystore_file: "/elasticsearch/plugins/readonlyrest/keystore.jks"
keystore_pass: readonlyrest
key_pass: readonlyrest
response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
access_control_rules:
- name: "::LOGSTASH::"
auth_key: logstash:logstash
type: allow
actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
indices: ["logstash-*", "<no-index>"]
- name: "::KIBANA-SRV::" …
```

Fixing #110 and #111

---

README.md
src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/LdapConfig.java
src/main/java/org/elasticsearch/plugin/readonlyrest/ldap/UnboundidLdapClient.java
src/test/resources/test_elasticsearch.yml

Now you can override `uid` and `uniqueMember` attributes.
Example config:
```
ldaps:
- name: ldap1
host: {LDAP1}
port: 389                                                 # default 389
ssl_enabled: false                                        # default true
ssl_trust_all_certs: true                                 # default false
bind_dn: "cn=admin,dc=example,dc=com"                     # skip for anonymous bind
bind_password: "password"                                 # skip for anonymous bind
search_user_base_DN: "ou=People,dc=example,dc=com"
search_groups_base_DN: "ou=Groups,dc=example,dc=com"
user_id_attribute: "uid"                                  # default "uid"
unique_member_attribute: "uniqueMember"                   # default "uniqueMember"
connection_pool_size: 10 …
```

changed: ldap user id and user refernce attributes from config

---

src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/Block.java
src/test/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/BlockTest.java

This PR implements the order suggested in the forum thread.
1. Auth related rules - those that implement UserRule interface
2. Rules that inspect the request - all the remaining ones
3. Rewrite rules - currently, only IndicesRewrite
I hope all the rules are in the appropiate set 😄 
The first commit also implements a test case to ensure the established order is observed.
Unfortunately, due to the previous implementation using a hashmap,  there's a slight chance the test case would pass even if implementation under test doesn't guarantee the required order.

Order sync rules: auth, inspect, mutate

---

core/src/main/java/tech/beshu/ror/acl/definitions/DefinitionsFactory.java
core/src/main/java/tech/beshu/ror/acl/definitions/ldaps/unboundid/UnboundidGroupsProviderLdapClient.java
core/src/main/java/tech/beshu/ror/acl/definitions/ldaps/unboundid/UserGroupsSearchFilterConfig.java
core/src/main/java/tech/beshu/ror/settings/definitions/GroupsProviderLdapSettings.java
core/src/test/java/tech/beshu/ror/acl/definitions/ldaps/UnboundidGroupsProviderLdapClientTests.java
core/src/test/resources/test_example.ldif

This allows the LDAP authorization connector to fetch groups from the memberOf or other multi-value attribute from the user rather than doing the lookup on a group. This is especially helpful when using recursive groups.
Two new configuration options have been added:
`groups_from_user` a boolean used to toggle between fetching from the group or from an attribute on the user. Default: `false` (fetch from group, current functionality)
`groups_from_user_attribute` a string used to indicate which property to check on the user. Default: `memberOf`
The `UnboundidGroupsProviderLdapClientTests` class has been largely refactored to include the new functionality and ensure parity. Additionally a check for empty results has been added.

(LDAP) Allow for fetching groups from a multi-value attribute on the user

---

core/src/main/java/tech/beshu/ror/acl/definitions/DefinitionsFactory.java
core/src/main/java/tech/beshu/ror/httpclient/ApacheHttpCoreClient.java
core/src/main/java/tech/beshu/ror/settings/definitions/ExternalAuthenticationServiceSettings.java
core/src/test/java/tech/beshu/ror/settings/ExternalAuthenticationSettingsTests.java

If validate option is false, host name verification and certificate validation are turned off.
Default is true which preserves b/c

add external auth validate option

---

bin/build.sh
commons/src/main/java/tech/beshu/ror/commons/settings/RawSettings.java
core/src/main/java/tech/beshu/ror/acl/blocks/rules/impl/JwtAuthSyncRule.java
core/src/main/java/tech/beshu/ror/settings/AuthMethodCreatorsRegistry.java
core/src/main/java/tech/beshu/ror/settings/RorSettings.java
core/src/main/java/tech/beshu/ror/settings/definitions/JwtAuthDefinitionSettings.java
core/src/main/java/tech/beshu/ror/settings/definitions/JwtAuthDefinitionSettingsCollection.java
core/src/main/java/tech/beshu/ror/settings/rules/JwtAuthRuleSettings.java
core/src/test/java/tech/beshu/ror/acl/blocks/BlockTest.java
core/src/test/java/tech/beshu/ror/acl/blocks/rules/impl/JwtAuthRuleTests.java
integration-tests/src/test/java/tech/beshu/ror/integration/JwtAuthTests.java
integration-tests/src/test/resources/jwt_auth/elasticsearch.yml

Hi !
This pull request allows a role base-based access controls on a jwt_auth.
Instead of repeat the jwt_auth configuration,  we define now a list of jwts providers
This is an example for a keycloak provider.
```yml
readonlyrest:
access_control_rules:
- name: Valid JWT token with a viewer role
jwt_auth:
name: "keycloak"
roles: ["viewer"]
jwt: 
- name: keycloak
signature_algo: RSA
signature_key: "your_signature"
user_claim: email
roles_claim: resource_access.client-app.roles
header_name: Authorization
```

jwt_auth: role-based access controls

---

README.md
core/src/main/java/tech/beshu/ror/acl/definitions/DefinitionsFactory.java
core/src/main/java/tech/beshu/ror/acl/definitions/groupsproviders/GroupsProviderServiceHttpClient.java
core/src/main/java/tech/beshu/ror/httpclient/ApacheHttpCoreClient.java
core/src/main/java/tech/beshu/ror/httpclient/RRHttpRequest.java
core/src/main/java/tech/beshu/ror/settings/definitions/UserGroupsProviderSettings.java
core/src/test/java/tech/beshu/ror/acl/blocks/rules/impl/GroupsProviderAuthorizationAsyncRuleTests.java
core/src/test/resources/group_provider_authorization_complex.json

Updated the Group Service Configurations to support static headers and parameters to be configured.
Some API's need basic auth, some need Hmac token as request param, which can be statically configured in the configuration Yml. New updates won't affect the existing configurations and won't take effect unless configured.

Configurable headers and parameters for Group Service Api Calls.

---

commons/src/main/java/tech/beshu/ror/commons/shims/request/RequestContextShim.java
core/src/test/java/tech/beshu/ror/core/requestcontext/SerializationToolTests.java

This is to enable including the body of the request in the custom
AuditLogSerializer.
This method was already provided in all concrete implementation, this is just exposing it via the interface.

Add getContent() method to the RequestContextShim interface.

---

core/src/main/java/tech/beshu/ror/requestcontext/DefaultAuditLogSerializer.java
core/src/test/java/tech/beshu/ror/core/requestcontext/SerializationToolTests.java

As the consequence, "match" and "block" were never included in the
audit log entry.

Result map was created but never used.

---

core/src/main/java/tech/beshu/ror/requestcontext/QueryAuditLogSerializer.java

The default serializer does not log the user request, e.g. what a user is searching for, which is necessary for some audit requirements.
This extended serializer logs the content part of the user's request.
It can be enabled by the configuratiion:
audit_serializer: tech.beshu.ror.requestcontext.QueryAuditLogSerializer
If this pull request is successful I will do a pull request in the docs github to provide an example.

Added QueryAuditSerializer which logs request content

---

core/src/main/java/tech/beshu/ror/acl/blocks/rules/impl/JwtAuthSyncRule.java

When using external validator in jwt_auth rule,
avoid ArrayIndexOutOfBoundsException to be thrown when JWT is not valid

fix issue [jwt_auth rule throws ArrayIndexOutOfBoundsException #390] :

---

core/src/main/java/tech/beshu/ror/acl/blocks/rules/impl/JwtAuthAsyncRule.java
core/src/main/java/tech/beshu/ror/settings/definitions/JwtAuthDefinitionSettings.java
core/src/main/java/tech/beshu/ror/settings/rules/JwtAuthRuleSettings.java
core/src/test/java/tech/beshu/ror/acl/blocks/rules/impl/JwtAuthRuleTests.java
es63x/src/main/java/tech/beshu/ror/es/RequestInfo.java
integration-tests/src/test/java/tech/beshu/ror/integration/JwtAuthTests.java
integration-tests/src/test/resources/jwt_auth/elasticsearch.yml

I'm saving the token in cookies (https://docs.micronaut.io/latest/guide/index.html#cookieToken), so by default, the request is sent with a different header.
For example, instead of Authorization: Bearer <token>, allow this: Cookie: JWT=<token>

Allow custom jwt header prefix

---

core/src/main/java/tech/beshu/ror/acl/definitions/DefinitionsFactory.java
core/src/main/java/tech/beshu/ror/httpclient/ApacheHttpCoreClient.java
core/src/main/java/tech/beshu/ror/settings/HttpConnectionSettings.java
core/src/main/java/tech/beshu/ror/settings/definitions/ExternalAuthenticationServiceSettings.java
core/src/main/java/tech/beshu/ror/settings/definitions/JwtAuthDefinitionSettings.java
core/src/main/java/tech/beshu/ror/settings/definitions/UserGroupsProviderSettings.java
core/src/main/java/tech/beshu/ror/settings/rules/JwtAuthRuleSettings.java
core/src/test/java/tech/beshu/ror/acl/blocks/rules/impl/JwtAuthRuleTests.java
core/src/test/java/tech/beshu/ror/settings/ExternalAuthenticationSettingsTests.java

LDAP is already configurable, but this does not seem to be the case for other external autentication providers.
I considered adding a retry handler, but it doesn't look like that is supported in AsyncHttpClient, so it's probably better to not clutter things with some custom implementation of that (at least for now!).
Remaining work:

Made HTTP Connection configurable

---

core/src/main/scala/tech/beshu/ror/acl/blocks/rules/JwtAuthRule.scala
core/src/main/scala/tech/beshu/ror/acl/blocks/rules/RorKbnAuthRule.scala
core/src/main/scala/tech/beshu/ror/acl/domain.scala
core/src/main/scala/tech/beshu/ror/acl/factory/decoders/common.scala
core/src/main/scala/tech/beshu/ror/acl/factory/decoders/definitions/ExternalAuthorizationServicesDecoder.scala
core/src/main/scala/tech/beshu/ror/acl/factory/decoders/definitions/JwtDefinitionsDecoder.scala
core/src/main/scala/tech/beshu/ror/acl/utils/ClaimsOps.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/JwtAuthRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/JwtAuthRuleSettingsTests.scala

Fixed bug reported on:
https://forum.readonlyrest.com/t/issue-with-auth0-jwt-roles/1174/2

fixed: jsonpath lib used as ClaimName

---

core/src/main/scala/tech/beshu/ror/acl/blocks/definitions/ldap/implementations/UnboundidLdapService.scala
core/src/main/scala/tech/beshu/ror/acl/factory/decoders/definitions/LdapServicesDecoder.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/definitions/UnboundidLdapAuthorizationServiceTests.scala

Hi,
Apache allows to authorize an user with its dn or uid (cf. http://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html#authldapgroupattributeisdn). This change adds a boolean to reproduce Apache behavious with RoR. It solves #402, #300, and #478.
Best regards.

Add a boolean group_attribute_is_dn to query user_dn or user_uid

---

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/definitions/ldap/implementations/UnboundidLdapConnectionPoolProvider.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/definitions/ldap/implementations/UnboundidLdapService.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/definitions/LdapServicesDecoder.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/rules/LdapRulesDecoders.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/utils/LdapConnectionPoolOps.scala
core/src/main/scala/tech/beshu/ror/boot/SchedulerPools.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/definitions/UnboundidLdapAuthenticationServiceTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/definitions/UnboundidLdapAuthorizationServiceTests.scala
gradle.properties

🐞Fix (ES) better LDAP request timeout handling
🧐Enhancement (ES) LDAP connection pool improvement

[RORDEV-235] unboundId request timeout handling + all queries will be made on separate, io executor

---

core/src/main/scala/tech/beshu/ror/accesscontrol/AccessControl.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/acl/AccessControlList.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/Block.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/BlockContext.scala
core/src/test/scala/tech/beshu/ror/unit/acl/AccessControlListTests.scala
gradle.properties

🐞Fix (ES) available groups order in metadata response should match the order in which groups appear in ACL

[RORDEV-273] bugfix - available group order in user metadata response

---

core/src/main/scala/tech/beshu/ror/boot/ReadonlyRest.scala
core/src/main/scala/tech/beshu/ror/configuration/RorProperties.scala
proxy/src/main/scala/tech/beshu/ror/proxy/Boot.scala
proxy/src/main/scala/tech/beshu/ror/proxy/ProxyEnvSettings.scala
proxy/src/main/scala/tech/beshu/ror/proxy/RorProxy.scala

ROR Proxy supports SUPERUSER basic authentication - it means that each downstream request (from proxy to underlying ES) will be enriched with authentication header. Superuser name and secret can be defined by setting following environment variables: `ROR_SUPERUSER_NAME` & `ROR_SUPERUSER_SECRET`

[RORDEV-306] proxy superuser support

---

es55x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es60x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es61x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es62x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es63x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es66x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es70x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es72x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es73x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es74x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es77x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es78x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
es79x/src/main/scala/tech/beshu/ror/es/request/context/types/ClusterAllocationExplainEsRequestContext.scala
gradle.properties
integration-tests/src/test/resources/cluster_api/readonlyrest.yml
integration-tests/src/test/scala/tech/beshu/ror/integration/suites/ClusterApiSuite.scala

🐞Fix (ES) /_cluster/allocation/explain request should not be forbidden if matched block doesn't have `indices` rules

[RORDEV-335]: allocation explain request fix

---

es55x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es60x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es61x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es62x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es63x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es66x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es70x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es710x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es72x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es73x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es74x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es77x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es78x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
es79x/src/main/scala/tech/beshu/ror/es/request/queries/QueryFieldsUsage.scala
gradle.properties

🐞Fix (ES) [removed verbose logging](https://forum.readonlyrest.com/t/elastic-message-cannot-extract-fields-for-query-after-readonlyrest-installation/1749)

[RORDEV-392] removed verbose logging

---

core/build.gradle
gradle.properties
ror-shadowed-libs/build.gradle

🚨Security Fix (ES) [CVE-2020-35490](https://nvd.nist.gov/vuln/detail/CVE-2020-35490) & [CVE-2020-35490](https://nvd.nist.gov/vuln/detail/CVE-2020-35491)

[RORDEV-398] upgraded: fasterXML jackson-databind lib - CVE-2020-35490 & CVE-2020-35491

---

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/KibanaAccessRule.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/KibanaAccessRuleTests.scala

fix #685 Saved Search short url creation has changed in Kibana/Elastic 7.8.1, this pull request add a new pattern to allow RO users to create short url.

add regex for short URL creation on ES 7.8.1

---

bin/build.sh
bin/upload_es_artifacts.sh
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/JwtAuthRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/LdapAuthorizationRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/RorKbnAuthRule.scala
core/src/test/scala/tech/beshu/ror/mocks/MockRequestContext.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/BaseGroupsRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/ExternalAuthorizationRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/JwtAuthRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/LdapAuthorizationRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/RorKbnAuthRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/JwtAuthRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/RorKbnAuthRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala
es716x/src/main/scala/tech/beshu/ror/es/handler/AclAwareRequestFilter.scala
es82x/gradle.properties
gradle.properties

🐞Fix (ES|KBN) tenancy selector didn't work well with `jwt_auth` and `ror_kbn_auth` rules

[RORDEV-687] fixed: currently group in context of `jwt_auth` and `ror_kbn_auth` rule

---

azure-pipelines.yml
core/src/main/scala/tech/beshu/ror/accesscontrol/acl/AccessControlList.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/Block.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/metadata/UserMetadata.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/BaseGroupsRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/JwtAuthRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/RorKbnAuthRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/logging/AccessControlLoggingDecorator.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/request/RequestContext.scala
core/src/test/scala/tech/beshu/ror/integration/CurrentUserMetadataAccessControlTests.scala
core/src/test/scala/tech/beshu/ror/integration/GroupsRuleAccessControlTests.scala
core/src/test/scala/tech/beshu/ror/integration/KibanaIndexAndAccessYamlLoadedAccessControlTests.scala
core/src/test/scala/tech/beshu/ror/integration/RorKbnAuthYamlLoadedAccessControlTests.scala
core/src/test/scala/tech/beshu/ror/mocks/MockRequestContext.scala
core/src/test/scala/tech/beshu/ror/unit/acl/AccessControlListTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/BaseGroupsRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/FieldsRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/FilterRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/GroupsOrRuleTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/variables/RuntimeResolvableVariablesTests.scala
core/src/test/scala/tech/beshu/ror/utils/TestsUtils.scala
gradle.properties

🐞Fix (ES|KBN) tenancy selector didn't work well with jwt_auth and ror_kbn_auth rules

[RORDEV-687] `jwt_rule`, `ror_kbn_auth` and local groups mapping fix

---

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/metadata/MetadataValue.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/BaseKibanaRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/kibana/KibanaAccessRuleSettingsTests.scala
gradle.properties

fixes to: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/888

[RORDEV-834] Kibana access 'api_only' was not handled everywhere in the ROR's code

---

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/BaseKibanaRule.scala
core/src/test/scala/tech/beshu/ror/unit/acl/blocks/rules/kibana/BaseKibanaAccessBasedTests.scala
gradle.properties

fix: in Kibana 8.8.0 we need to match kibana request that is related to two kibana indices at the same time

[RORDEV-907] Kibana 8.8.0 related `kibana` rule adaptations

---

core/build.gradle
core/src/main/scala/tech/beshu/ror/Constants.java
core/src/test/scala/tech/beshu/ror/integration/KibanaIndexAndAccessYamlLoadedAccessControlTests.scala
gradle.properties

🐞Fix (ES) kibana access `rw` and `admin` should allow to manage component templates
🚨Security Fix (ES) [CVE-2023-34462](https://github.com/advisories/GHSA-6mjq-h674-j845)

[RORDEV-902] kibana access `rw` and `admin` should allow to manage component templates

---

core/src/main/scala/tech/beshu/ror/accesscontrol/domain.scala
es710x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/datastreams/GetDataStreamEsRequestContext.scala
es711x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/datastreams/GetDataStreamEsRequestContext.scala
es714x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/datastreams/GetDataStreamEsRequestContext.scala
es716x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/datastreams/GetDataStreamEsRequestContext.scala
es79x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/datastreams/GetDataStreamEsRequestContext.scala
es80x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/datastreams/GetDataStreamEsRequestContext.scala
es81x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es81x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
es82x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es82x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
es83x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es83x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
es84x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es84x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
es85x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es85x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
es87x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es87x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
es88x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es88x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
es89x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/DataStreamsStatsEsRequestContext.scala
es89x/src/main/scala/tech/beshu/ror/es/handler/request/context/types/GetDataStreamEsRequestContext.scala
gradle.properties
integration-tests/src/test/resources/data_stream_api/readonlyrest.yml
integration-tests/src/test/scala/tech/beshu/ror/integration/suites/DataStreamApiSuite.scala

🐞Fix (ES) [getting data streams when not full names of backing indices are declared in the `indices` rule](https://forum.readonlyrest.com/t/forbidden-for-creating-component-templates/2372/7)

[RORDEV-931] fix: getting data streams API

---

bin/build-ror-plugin.sh
docker-envs/build-ror-in-docker/build.sh

You can build many ROR deliverables at once:
e.g.
```bash
docker-envs/build-ror-in-docker/build.sh 8.10.1 8.10.0
```

[RORDEV-851] building ES ROR in docker - improvements 

---

core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/BaseKibanaRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/KibanaAccessRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/KibanaHideAppsRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/KibanaIndexRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/KibanaTemplateIndexRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/blocks/rules/kibana/KibanaUserDataRule.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/factory/BlockValidator.scala
core/src/main/scala/tech/beshu/ror/accesscontrol/ops.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/CoreFactoryTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/JwtAuthRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/ProxyAuthRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/RorKbnAuthRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/elasticsearch/FieldsRuleSettingsTest.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/elasticsearch/ResponseFieldsRuleSettingsTest.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/kibana/KibanaAccessRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/kibana/KibanaHideAppsRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/kibana/KibanaIndexRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/kibana/KibanaUserDataRuleSettingsTests.scala
gradle.properties
integration-tests/src/test/resources/duplicated_response_headers_issue/readonlyrest.yml

🧐Enhancement (ES) additional [validations](https://docs.readonlyrest.com/elasticsearch#configuring-an-acl-with-filter-fields-rules-when-using-kibana): `kibana` rule should not be used with some other rules in the same block

[RORDEV-1128] additional validations: `kibana` rule should not be used with some other rules in the same block

---

core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/definitions/UsersDefinitionsDecoder.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/GroupsRuleSettingsTests.scala
gradle.properties

🐞Fix (ES) configuration parsing regression: one group definition can be a string

[RORDEV-1178] regression fix: `groups` defined as string not only array of strings

---

core/build.gradle
tests-utils/src/main/scala/tech/beshu/ror/utils/misc/EsStartupChecker.scala

Fixes:
- ES container startup timeout was reduced to 1 minute, instead of intended 2 minutes, now restored to the 5 minutes default from before Scala 3 migration
- testcontainers-scala downgraded back to 0.40.17 - I could not consistently reproduce it, but there may be a bug in 0.41.x, that manifests when using Dockerfile and copying files (testcontainers-java/issues/1348, testcontainers-java/issues/7239)

[RORDEV-1152] ES testcontainer fixes

---

core/src/main/scala/tech/beshu/ror/accesscontrol/factory/decoders/definitions/LdapServicesDecoder.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/definitions/LdapServicesSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/LdapAuthRuleSettingsTests.scala
core/src/test/scala/tech/beshu/ror/unit/acl/factory/decoders/rules/auth/LdapAuthorizationRuleSettingsTests.scala
gradle.properties

"sever_side_groups_filtering" -> "server_side_groups_filtering"
The fix is backward compatible. We still support the setting name with the typo.

[RORDEV-1202] fixed: typo in LDAP server side filtering setting name

---

es716x/Dockerfile
es717x/Dockerfile
es80x/Dockerfile
es810x/Dockerfile
es811x/Dockerfile
es812x/Dockerfile
es813x/Dockerfile
es814x/Dockerfile
es815x/Dockerfile
es816x/Dockerfile
es818x/Dockerfile
es81x/Dockerfile
es82x/Dockerfile
es83x/Dockerfile
es84x/Dockerfile
es85x/Dockerfile
es87x/Dockerfile
es88x/Dockerfile
es89x/Dockerfile

In this PR:
1. Fixed Docker image creation for ES 8.17.6
2. A consistent method of `gosu` installation for all ES versions

[RORDEV-1464] fixed: 8.17.6 docker image + consistent method of installing gosu

---

gradle.properties
ror-tools/src/main/scala/tech/beshu/ror/tools/RorToolsApp.scala
ror-tools/src/test/scala/tech/beshu/ror/tools/RorToolsAppSuite.scala

- 🐞Fix (ES) Docker images now start correctly when `I_UNDERSTAND_AND_ACCEPT_ES_PATCHING` is set.
---
Currently:
1. No ENV set (result: :white_check_mark:)
```
$ docker run -ti -u root -p 9202:9200 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e ADMIN_USER_PASS=admin beshultd/elasticsearch-readonlyrest:9.0.3-ror-1.65.0 bash
WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by tech.beshu.ror.tools.scala.runtime.LazyVals$ (file:/usr/share/elasticsearch/plugins/readonlyrest/ror-tools.jar)
WARNING: Please consider reporting this to the maintainers of class tech.beshu.ror.tools.scala.runtime.LazyVals$
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
Checking …
```

[RORDEV-1501] docker images issue with accepting consent 
